### ISSUE TITLE
Max's Requests

### ISSUE THREAD

**Issue by tessguefen** [tessguefen/Components-Layouts#1]
- [ ] Code field (required) unique per Layout, on update of module, auto fill the ID of the cmp
- [x] Display Order for Components
- [x] Add component code to modal window at the top
- [x] "Array"-style component field

**Comment by tessguefen** [comment]
Add Layout Column for Transient Code
- Check if Transient active
- If transient active, clear transient/ delete based on code

**Comment by mghweb** [comment]
Add an "Array" or "List" style component field.

The database would store the values as a pipe separated string. The view within the admin will look and function similar to the new Multi-Value custom field type.

The pipe separated string will be converted to new line delimited and displayed within the pared-down code view box. When saved, it will convert back to pipes.

When outputting the layout in JSON or MVT the `:value` value will be an array; not a pipe separated string.

Thanks 😄

**Comment by mghweb** [comment]
Add an interface within the Export section to export only a single layout?

**Comment by tessguefen** [comment]
> Add an interface within the Export section to export only a single layout?
> 
> -- similar to how you can export only a single category's worth of products

How about in the Batchlist, if you select one, adding a CTA to prompt the XML download? This would exclude any components. Just the layout.

**Comment by tessguefen** [comment]
> Add an interface within the Export section to export only a single layout?
> 
> -- similar to how you can export only a single category's worth of products

Done.
